### Create User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "testpassword"
}


### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json;

{
  "email": "test@example.com",
  "password": "testpassword"
}
