### Get Expense by ID
GET http://localhost:8080/api/v1/expenses/1
Authorization: Bearer {{token}}

### Get All Expenses by User ID
GET http://localhost:8080/api/v1/expenses/user/1
Authorization: Bearer {{token}}

### Create Expense
POST http://localhost:8080/api/v1/expenses
Authorization: Bearer {{token}}
Content-Type: application/json;

{
  "userId": 1,
  "amount": 50.00,
  "date": "2024-04-22",
  "category": "Food",
  "description": "Lunch at a restaurant"
}

### Update Expense
PUT http://localhost:8080/api/v1/expenses/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "amount": 35.00,
  "date": "2024-04-22",
  "category": "Food",
  "description": "Dinner at home"
}

### Delete Expense
DELETE http://localhost:8080/api/v1/expenses/1
Authorization: Bearer {{token}}
