### Get User by ID
GET http://localhost:8080/api/v1/users/1
Authorization: Bearer {{token}}

### Get User by Username
GET http://localhost:8080/api/v1/users/username/john_doe
Authorization: Bearer {{token}}

### Get User by Email
GET http://localhost:8080/api/v1/users/email/john@example.com
Authorization: Bearer {{token}}

### Update User
PUT http://localhost:8080/api/v1/users/1
Authorization: Bearer {{token}}
Content-Type: application/json;

{
  "password": "testpassword"
}
